services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ProductDb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

  webapi:
    build: . # image: images.mysite.com/webapi:1
    depends_on:
      - db
    environment:
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=ProductDb;Username=postgres;Password=postgres
      - ASPNETCORE_ENVIRONMENT=${ENVIRONMENT_NAME}
    ports:
      - "80:8080"
    restart: always

volumes:
  pgdata:
